export type TelegramChannel = {
  id: string;
  title: string;
  handle: string;
  url: string;
  description?: string;
  image?: string | null;
  clusters?: string[];
  interestSlugs?: string[];
  interestTitles?: string[];
  language?: "ru" | "en";
  priority?: number;
};

export const TELEGRAM_CHANNELS: TelegramChannel[] = [
  {
    id: "tg:habr",
    title: "Habr",
    handle: "habr_com",
    url: "https://t.me/habr_com",
    description: "Главные публикации Хабра о разработке, инженерии и продуктовых подходах.",
    clusters: ["tech"],
    interestSlugs: ["coding", "ai", "data-analytics"],
    language: "ru",
    priority: 3,
  },
  {
    id: "tg:tproger",
    title: "Tproger",
    handle: "tproger",
    url: "https://t.me/tproger",
    description: "Статьи и подборки для разработчиков: бэкенд, фронтенд, карьера и софт-скиллы.",
    clusters: ["tech"],
    interestSlugs: ["coding", "career"],
    language: "ru",
    priority: 3,
  },
  {
    id: "tg:datatalksclub",
    title: "DataTalks.Club",
    handle: "datatalksclub",
    url: "https://t.me/datatalksclub",
    description: "Сообщество аналитиков и инженеров данных: митапы, подкасты и открытые материалы.",
    clusters: ["tech"],
    interestSlugs: ["data-analytics", "ai"],
    language: "en",
    priority: 3,
  },
  {
    id: "tg:vcru",
    title: "vc.ru",
    handle: "vcru",
    url: "https://t.me/vcru",
    description: "Новости и разборы про технологический бизнес, стартапы и цифровые продукты.",
    clusters: ["tech", "business"],
    interestTitles: ["Стартапы", "Продуктовый менеджмент"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:productstar",
    title: "ProductStar",
    handle: "productstar",
    url: "https://t.me/productstar",
    description: "Практики продуктового менеджмента, карьера в IT и подборка лучших материалов.",
    clusters: ["tech", "business"],
    interestSlugs: ["product-management", "career"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:skillbox",
    title: "Skillbox",
    handle: "skillboxru",
    url: "https://t.me/skillboxru",
    description: "Короткие разборы и подборки курсов по дизайну, разработке, аналитике и менеджменту.",
    clusters: ["tech", "learning"],
    interestSlugs: ["coding", "design", "data-analytics"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:setters",
    title: "SETTERS",
    handle: "setters",
    url: "https://t.me/setters",
    description: "Маркетинг, брендинг и коммуникации: кейсы агентства SETTERS и полезные инструменты.",
    clusters: ["communication", "business"],
    interestSlugs: ["networking"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:englishdom",
    title: "EnglishDom",
    handle: "englishdom",
    url: "https://t.me/englishdom",
    description: "Советы по изучению английского языка, практика слов и подборка упражнений.",
    clusters: ["learning"],
    interestSlugs: ["languages"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:arzamas",
    title: "Arzamas",
    handle: "arzamas_academy",
    url: "https://t.me/arzamas_academy",
    description: "История, культура и гуманитарные лекции в коротком формате.",
    clusters: ["learning", "communication"],
    interestTitles: ["История", "Культура"],
    language: "ru",
    priority: 1,
  },
  {
    id: "tg:postnauka",
    title: "ПостНаука",
    handle: "postnauka",
    url: "https://t.me/postnauka",
    description: "Научпоп о биологии, физике, нейронауке и устройстве мира от исследователей.",
    clusters: ["learning", "tech"],
    interestTitles: ["Наука", "Научпоп"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:nplusone",
    title: "N+1",
    handle: "nplusone",
    url: "https://t.me/nplusone",
    description: "Новости науки и технологий, исследования и образовательные материалы.",
    clusters: ["learning", "tech"],
    interestTitles: ["Наука", "Технологии"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:tedrus",
    title: "TED на русском",
    handle: "TED_Rus",
    url: "https://t.me/TED_Rus",
    description: "Переводы TED Talks про образование, лидерство и коммуникации.",
    clusters: ["learning", "communication"],
    interestSlugs: ["public-speaking"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:publicspeaking",
    title: "Public Speaking",
    handle: "publicspeaking",
    url: "https://t.me/publicspeaking",
    description: "Советы и примеры по публичным выступлениям, сторителлингу и переговорам.",
    clusters: ["communication"],
    interestSlugs: ["public-speaking", "networking"],
    language: "en",
    priority: 2,
  },
  {
    id: "tg:lifehacker",
    title: "Лайфхакер",
    handle: "lifehacker_ru",
    url: "https://t.me/lifehacker_ru",
    description: "Продуктивность, привычки, софт-скиллы и бытовые лайфхаки каждый день.",
    clusters: ["self"],
    interestSlugs: ["productivity", "self-growth"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:biohacking",
    title: "Biohacking",
    handle: "biohacking",
    url: "https://t.me/biohacking",
    description: "Биохакинг, трекинг здоровья, сон и профилактика.",
    clusters: ["health", "self"],
    interestSlugs: ["fitness", "mental-health"],
    language: "ru",
    priority: 1,
  },
  {
    id: "tg:medach",
    title: "Медач",
    handle: "medach",
    url: "https://t.me/medach",
    description: "Разборы медицинских исследований и практики, доказательная медицина.",
    clusters: ["health"],
    interestTitles: ["Медицина", "Здоровье"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:doctorpiter",
    title: "Doctor Piter",
    handle: "doctorpiter",
    url: "https://t.me/doctorpiter",
    description: "Советы врачей о питании, сне, профилактике и здоровом образе жизни.",
    clusters: ["health"],
    interestSlugs: ["nutrition", "sleep"],
    language: "ru",
    priority: 1,
  },
  {
    id: "tg:investfuture",
    title: "InvestFuture",
    handle: "investfuture",
    url: "https://t.me/investfuture",
    description: "Личные финансы и инвестиции: аналитика рынков, подборки акций и обучающие материалы.",
    clusters: ["finance"],
    interestSlugs: ["investing", "personal-finance"],
    language: "ru",
    priority: 3,
  },
  {
    id: "tg:tinkoffinvest",
    title: "Тинькофф Инвестиции",
    handle: "tinkoff_invest",
    url: "https://t.me/tinkoff_invest",
    description: "Официальные материалы и подборки по личным инвестициям и рынку от Тинькофф.",
    clusters: ["finance"],
    interestSlugs: ["investing", "personal-finance"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:tinkoffjournal",
    title: "Т—Ж",
    handle: "tinkoffjournal",
    url: "https://t.me/tinkoffjournal",
    description: "Статьи про деньги, карьеру, образование и личную эффективность.",
    clusters: ["finance", "business", "self"],
    interestSlugs: ["personal-finance", "career", "productivity"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:thebell",
    title: "The Bell",
    handle: "thebell_io",
    url: "https://t.me/thebell_io",
    description: "Экономика, бизнес-кейсы и аналитика рынков понятным языком.",
    clusters: ["business", "finance"],
    interestTitles: ["Экономика", "Бизнес"],
    language: "ru",
    priority: 2,
  },
  {
    id: "tg:hbr",
    title: "Harvard Business Review Россия",
    handle: "hbr_ru",
    url: "https://t.me/hbr_ru",
    description: "Лидерство, стратегия, управление людьми и лучшие статьи HBR на русском.",
    clusters: ["business"],
    interestSlugs: ["leadership", "management", "career"],
    language: "ru",
    priority: 2,
  },
];
